name: PR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  check-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ./examples/demo

      - run: cargo check -p xtask
        working-directory: ./examples/demo

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable
          - msrv
        include:
          - os: ubuntu-latest
            rust: msrv
            lint: 1
          - rust: msrv
            rust-args: --all-features
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        shell: bash
        run: |
          ver="${{ matrix.rust }}"
          if [ "$ver" = msrv ]; then
              ver=$(cargo metadata --format-version 1 --no-deps | \
                  jq -r 'first(.packages[] | select(.rust_version != null).rust_version)')
              extra=(-c rustfmt -c clippy)
          fi
          rustup toolchain install "$ver" --profile minimal --no-self-update "${extra[@]}"
          rustup default "$ver"
          echo "Installed:"
          cargo --version
          rustc --version --verbose

      - uses: Swatinem/rust-cache@v2

      - run: rustup target add wasm32-unknown-unknown

      - run: cargo test --workspace ${{ matrix.rust-args }}

      - run: cargo fmt --all -- --check
        if: github.event_name == 'pull_request' && matrix.lint

      - run: cargo clippy --all --tests --all-features -- -D warnings
        if: github.event_name == 'pull_request' && matrix.lint
